package net.ninjacat.mk54.codegen;

import org.objectweb.asm.MethodVisitor;

import static org.objectweb.asm.Opcodes.*;


/**
 * Utility methods for code generation.
 * <p>
 * Code generated by these methods does not map to any of MK operations
 */
final class CodeGenUtil {

    static final String REGISTER_X = "x";
    static final String REGISTER_X1 = "x1";
    static final String REGISTER_Z = "z";
    static final String REGISTER_T = "t";
    static final String REGISTER_Y = "y";
    static final String REGISTER_X_MANTISSA = "xMantissa";
    static final String REGISTER_X_EXPONENT = "xExponent";
    static final String RESET_X = "resetX";

    static final String ENTRY_MODE = "entryMode";
    static final String DECIMAL_FACTOR = "decimalFactor";
    static final String CLASS_NAME = "net/ninjacat/mk54/Mk54";
    static final String CLASS_DESCRIPTOR = "L" + CLASS_NAME + ";";

    static final String JAVA_LANG_MATH = "java/lang/Math";

    private CodeGenUtil() {
    }


    /**
     * Moves stack down from T to Z and Z  to Y. This must be executed for every operation which
     * combines Y and X and puts result to X
     *
     * @param mv      Generated method visitor
     * @param context Code generation context
     */
    static void stackDown(final MethodVisitor mv, final CodeGenContext context) {
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, CLASS_NAME, REGISTER_Z, "F");
        mv.visitFieldInsn(PUTFIELD, CLASS_NAME, REGISTER_Y, "F");

        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, CLASS_NAME, REGISTER_T, "F");
        mv.visitFieldInsn(PUTFIELD, CLASS_NAME, REGISTER_Z, "F");
    }

    /**
     * Saves X to X1
     *
     * @param mv      Generated method visitor
     * @param context Code generation context
     */
    static void saveX(final MethodVisitor mv, final CodeGenContext context) {
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, CLASS_NAME, REGISTER_X, "F");
        mv.visitFieldInsn(PUTFIELD, CLASS_NAME, REGISTER_X1, "F");
    }

    /**
     * Helper method called on all operations. Sets resetX flag to true
     *
     * @param mv      Generated method visitor
     * @param context Code generation context
     */
    static void prepareXForReset(final MethodVisitor mv, final CodeGenContext context) {
        mv.visitVarInsn(ALOAD, 0);
        mv.visitInsn(ICONST_1);
        mv.visitFieldInsn(PUTFIELD, CLASS_NAME, RESET_X, "Z");
    }

    /**
     * Switches digit entry mode to exponent
     *
     * @param mv      Generated method visitor
     * @param context Code generation context
     */
    static void startExponent(final MethodVisitor mv, final CodeGenContext context) {
        mv.visitVarInsn(ALOAD, 0);
        mv.visitInsn(ICONST_1);
        mv.visitFieldInsn(PUTFIELD, CLASS_NAME, ENTRY_MODE, "I");
    }

}
